from __future__ import annotations

__version__ = "0.27.1"
__release__ = (
    "√−1 → 1: Core UEQGM aspects grounded in measured science. 8th-D field blend weights now the Planck 2018 cosmological census "
    "(dark energy, CDM, baryons, neutrinos, photons) measured by CMB survey, not hand-tuned. "
    "`holographic_entropy` = von Neumann graph entropy (HEHW quadratic) with dual-path signature: exact degree-pair sum via SQL, "
    "mean-degree fallback from counts — visible 0.0021 differential on live graph. "
    "`floquet_modulation_factor` = J₀(A/ω) dynamic localization (coherent destruction of tunneling), not cos(ωt). "
    "`hawking_information_remnant_score` = unitary Page curve w/ islands; Well geometric reference at Page time (0.5). "
    "Five Julia protocol peers mirrored. 78 core tests pass; zero regressions. "
    "Live smoke: 38-token vocab, 50 edges, 33ms train, 4ms gen, confidence 0.62."
)
__build_date__ = "2026-08-17"

PHASES = {
    "0.27.0": "System Entirety Control Plane GUI & GARD Shard High-Performance Neural Tensor Compression: Full 7-D System Entirety state re-materialization with non-zero sense manifold axes, local hardware asset discovery, active UEQGM adaptive runtime, multi-drive file selection, and GARD Shard authenticated container packing (gui/GARD_Shard/compression & gui/GARD_Shard/decompression) yielding 100% exact lossless binary file reconstruction with zero data dissociation error.",
    "0.26.0": "Doc annealing worker integrated (src/quipu/doc_annealing.py), the clean-room QUIPU reimplementation of the SCB living-map annealer. Each cycle reads the live 7+1-D System Entirety state, the MESH-SLM predictor snapshot, and the STP P1 trend, computes a SHA-256 structural fingerprint over version + bridge primary root + mesh_density + UEQGM certainty + nodal_bifurcation (each 2 dp), and rewrites docs/system_entirety_map.md only on structural change (or --force), bumping brain_kv['doc:system_map_version'] and appending a bounded doc_annealing:history entry. No RAG re-index (QUIPU ships none). anneal_docs/structural_change_review/render_system_map/run_loop public API + argparse CLI (--once/--loop/--interval/--force). Start-DocAnnealing.ps1 runs the loop; Register-DocAnnealing.ps1 installs a recurring 30-min Windows Scheduled Task. 5 focused tests in tests/test_doc_annealing.py.",
    "0.25.0": "STP-style geodesic diagnostic wired into mesh_slm.train_round() behind the QUIPU_STP_DIAGNOSTIC flag (default on, purely observational so it fails toward legacy like phase_weight/overlap). Each round samples a random 0<=s<r<t trajectory triplet per chunk and computes the Semantic-Tube-Prediction gap 1-cos(h_t-h_r, h_r-h_s) twice: over the learned 7-D embedding (paper-faithful hidden-state analogue) and over an isometric R^4 flat-torus embedding u=(cosθ,sinθ,cosφ,sinφ) of each token's (i,j) vocab cell (the QUIPU-native, wrap-aware-by-construction test). Per-round averages surface in the train_round summary (stp_embed_gap/stp_torus_gap) and state_summary, and capped rolling histories (stp_embed_gap_history, stp_torus_gap_history, loss_history) persist in mesh_slm_meta so the paper's P1 signature — ordinary loss plateaus while the STP gap keeps falling — is checkable via the read-only stp_diagnostic_trend() utility. No eta coupling (deliberately deferred Phase 2). Pure stdlib, no schema migration. 7 focused tests in tests/test_mesh_slm.py.",
    "0.24.1": "MESH-conditioned sigmoidal realization coupling for paired Vision and Touch agents. realized_potential.py adds a true logistic eligibility gate that requires bilateral evidence, prunes non-realized gradients before rADAM, retains them as bounded signed latent potential, and releases that potential when later evidence makes the interaction realizable. network_observer.py records a bounded 64-snapshot MESH history and exposes an exponentially weighted reader that admits only observations strictly before the forward decision time. brain_body_signals.py integrates the gate behind BRAIN_USE_REALIZATION_GATE=1, preserves legacy trajectories when disabled or history is absent, keeps quiet maintenance decay eligible, and persists per-pair diagnostics. 17 focused tests and adjacent observer/rADAM/learning-drive coverage pass (65 total).",
    "0.22.247": "mesh_compression_model.jl: added pack_weyl/unpack_weyl (20-byte v2.2 float-dimension brain_kv record, 5 x Float32 LE) plus the MESH_BRAIN_KV_WEYL_PACKED_BYTES constant, matching the ContosoHub v2.2 JS plane wire format. selftest() gained LE-canary, round-trip, and golden-base64 coverage for the new pack/unpack pair without altering the existing reconciled compaction-ratio/scalar assertions relied on by pipeline/tests/test_gard_shard_model.py.",
    "0.22.18": "System Entirety toroidal analysis and live operational pulse. Added docs/SYSTEM_ENTIRETY_ANALYSIS.md with a six-ring torus map (Perception → Dispatch → Self-train → Corpus → Refinement → Network/Compute) around the heart/system_entirety/torus_touch core, plus page inventory, daemon cohort, observability checklist, and release-time live metrics from _system_entirety_report.py. The document records that llm_dispatch_log contains only 10 rows total (all on 2026-05-04), self-train rounds are therefore replaying zero samples, refinement remains active with 14 open directives and 6 resilience events, and corpnet reachability from Codespaces is expected to fail outside the laptop/VPN/Dev Tunnel boundary. Verified with focused compile smoke and 53 passing system/mesh tests.",
    "0.22.14": "Mesh-applied network learner lock hardening and deep research queue recovery. network_learner.py now probes endpoints outside its SQLite write transaction, uses WAL plus busy_timeout, and writes topology in a short commit window so the autonomous mesh no longer self-deadlocks under probe latency. systemic_refinement_agent.py now calls the canonical deep_research table bootstrap helpers and uses a multi-token topic-gap detector instead of first-word matching, so deep-research tasks queue again. Applied to the live mesh by seeding a pending deep_research task and restarting the master agent after the shared workspace sync.",
    "0.22.12": "Vendor consolidation package cleanup and priority-driven workbook refresh. vendor_consolidation_excel.py now infers missing service levels from TCI service mode plus ship/delivery timing and supplier history instead of a flat 0.88 fallback, adds a filterable Priority_Tracker top-10 view with explicit solution updates and workbook routes, and links Summary/What_If directly to the active Priority 1 issue. The vendor consolidation handoff docs and CSV package metadata were refreshed to match the current workbook flow.",
    "0.22.10": "Credential fallback hardening and Grok Works Cited ingest resilience. llm_key_guard.py now fingerprints active secrets, prefers project-local .env values over stale inherited env vars, and clears backoff when a rotated key appears. llm_caller_openrouter.py now supports provider-aware backend resolution with direct xAI Grok fallback and normalized Grok aliases. doc_rag.py now reports credential provenance consistently from the active workspace key. knowledge_corpus.py resolves the newest available SCB export path, and citation_chain_acquirer.py now understands wrapped Works Cited paper_ids/seed_paper_ids payloads. Focused tests in tests/test_llm_key_guard.py, tests/test_llm_caller_openrouter.py, tests/test_doc_rag_credential.py, tests/test_citation_chain_acquirer_seeding.py, and tests/test_knowledge_corpus_scb_path.py.",
    "0.22.9": "Adaptive UEQGM runtime daemon and System Entirety consumption. ueqgm_engine.py now persists a certainty-gated adaptive runtime profile sourced from corpus density, recent learning_log evidence, and System Entirety certainty; parameters are retained unless newer evidence clears both the corpus-density floor and prior proof. synaptic_workers.py adds synapse-ueqgm for continuous runtime refresh. system_entirety.py now consumes the persisted UEQGM profile for symbiotic axis injection and transaction-drive overlay. Focused tests in tests/test_ueqgm_engine.py, tests/test_system_entirety.py, and tests/test_synaptic_workers.py.",
    "0.22.8": "Hideout Dev Tunnel diagnostics and resource-share planning. bridge_rdp.py adds hideout-rdp/hideout-mesh forwarding, mesh ping, doctor, and start helpers for the scbrain-hideout.use2 tunnel; compute_grid.py now exposes resource_inventory/resource_share_plan responses plus reusable ensure_devtunnel_endpoint() forwards; connect_hideout.ps1 persists the helper state without discarding the requested RemotePort. Focused tests in tests/test_compute_grid_devtunnel.py and tests/test_bridge_rdp.py, plus adjacent asset/geospatial/system-entirety validations green.",
    "0.22.7": "Asset Resource Mesh for System Entirety physical realization. asset_resource_mesh.py materializes compute-grid peers into ComputePeer and AssetResource nodes for cores/RAM/VRAM; writes HAS_ASSET, REALIZES_MATERIAL_PROCESSOR, ASSET_RESOURCE_TUNNEL, and SYSTEM_ENTIRETY_REALIZES edges; persists asset_resource_mesh_last and brain_kv['entirety:physical_realization']; torus_touch ACTIVE_TORUS_ENTITY_TYPES now includes AssetResource; peer_inject runs _phase_asset_mesh after capacity publish so compute assets become graph-tunnel substrate each cycle. Focused tests in tests/test_asset_resource_mesh.py.",
    "0.22.6": "Physical material science processor level for actualized space. geospatial_relation.py now materializes OCR world-pose anchors into SpatialMaterialProcessor corpus nodes with ACTUALIZED_SPACE_FRAME=ENU_METER_WORLD_V1, covariance_diag_m2, material_structure, source ACTUALIZES_SPACE edges, and endpoint torus amplification from MATERIAL_ANCHOR precision. torus_touch.tick_torus_pressure now includes ACTIVE_TORUS_ENTITY_TYPES=(Endpoint, SpatialMaterialProcessor), with typed velocity keys and processor diagnostics. symbiotic_tunnel.vision_horizontal_expand folds MATERIAL_ANCHOR processor certainty into endpoint propeller weights so tunnel routing uses the standardized physical substrate. grounded_tunneling.compute_endpoint_certainty reads material-anchor precision for endpoint grounding without treating processors as endpoints. peer_inject logs processor/amplification stats. 17 focused unit tests in tests/test_geospatial_relation.py plus 38 existing torus/tunnel tests green.",
    "0.22.5": "Dependency vulnerability remediation: requirements.txt now pins safe floors for Pillow, GitPython, and urllib3; requirements.pinned.txt updated to the fixed versions; verified with pip-audit against both the live pipeline venv and requirements.txt.",
    "0.22.3": "GeoGraph Spatial Relation Bridge. geospatial_relation.py: CameraIntrinsics + SensorPose + unproject_pixel (pinhole sensor\u2192world) and haversine_destination/haversine_distance_m (great-circle raycast). relate_detection runs both derivations and fuses by inverse-variance; anchor_entity persists the Bayesian-blended posterior on corpus_entity.props_json.world_pose with statistical (residual-z) and probabilistic (\u03c3\u207b\u00b2 saturating) certainties. couple_anchors_to_torus writes bearing\u2192TORUS_SPATIAL_DIM(0) and log-range\u2192TORUS_RANGE_DIM(1), so the CatGapField sinusoidal envelope converts physical-space geometry into Touch pressure on the next tick_torus_pressure pass. strengthen_peer_mesh mints MATERIAL_ANCHOR edges from Endpoint entities within PEER_MESH_RADIUS_M=50 m of a material-anchor entity, EMA-blended on reinforcement. tick_geospatial_relation orchestrates the full pass for peer_inject. 12 unit tests in tests/test_geospatial_relation.py.",
    "0.22.2": "Corpus freshness watchdog in app.py now distinguishes autonomous process liveness from corpus learning freshness; synaptic torus-touch and compute-slot workers use WAL-mode connections plus transient lock retry/backoff; System Entirety retains reliable audited flip history under lock contention.",
    "0.20.18": "Routed page hardening + 26-route primary-UI smoke; honest DBI first-user-state on heavy pages.",
    "0.1.0": "Phase 1 - core (EOQ Bayesian-Poisson, OTD recursive, Procurement 360, Data Quality, Connectors)",
    "0.2.0": "Phase 2 - depth (graph backends, LinUCB ranker, hierarchical OTD index)",
    "0.3.0": "Phase 3 - MIT CTL research (hierarchical EOQ, causal lead-time, survival, bullwhip, multi-echelon, sustainability, freight portfolio, CVaR risk)",
    "0.4.0": "Phase 4 - platform (what-if sandbox, HMAC cross-app webhooks, nightly fact builder, session auth)",
    "0.4.1": "Self-driving pages, fixed MPA sidebar slugs, schema-browser diagnostics on live failures",
    "0.4.2": "All 14 pages Plotly rewrite complete; page_header/drilldown_table retired; DQ VOI heatmaps; Connectors modernized",
    "0.4.3": "Bug-fix wave: VOI Timestamp/datetime handling, graph node-kind propagation + discovery panel, EOQ outlier heatmap+quadrant, Procurement 360 supplier/part name lookups, Benchmarks rows_per_s merge collision, sidebar filter wiring",
    "0.4.4": "Pages 7-12 SQL queries rewritten against base replica tables; eliminates dependency on missing vw_* views",
    "0.4.5": "YYYYMMDD integer-date fix all research pages; session_state SQL cache kills HYT00 timeout cascade; graph node labels enriched; timeout 120 s globally; connection health-check ping",
    "0.4.6": "Unified Database Explorer with auto-parsed schema reviews from DATA_DICTIONARY and DWH_DASHBOARD_TABLES",
    "0.5.0": "Value Stream Living Map: End-to-end integration of PO, SO, WO flows. Formulaic friction bottlenecks. Production Plant and Value Stream filtering.",
    "0.6.0": "Global Application Filter, unified st.session_state routing, and AI PowerPoint Creator.",
    "0.7.0": "Enterprise Network Autonomous Agent. Native Exchange/SMB discovery.",
    "0.7.1": "Ask the Data cross-dataset report generation. Fixed global connection uninitialized bug. Fixed SQL column queries across analytical pages.",
    "0.8.0": "Massive UX/Actionable overhaul: SQLite local store, NLP-part categorization, Global date windows, semantic action-TODO engine, OTD local-owner tracking, and cross-page metric fixes.",
    "0.14.9": "OCW semantic bridge + synaptic worker protection + network vision worker. Workers moved to synaptic_workers.py. Sweeper treats network errors as soft skips. _vision_worker probes bridge_rdp + piggyback topology every 5 min and materialises Endpoint entities into corpus graph.",
    "0.15.0": "4-ERP xlsx pipeline (Epicor/Oracle/SyteLine/AX) + Brain page fixes + EOQ query optimisation.",
    "0.16.0": "Symbiotic Dynamic Tunneling + Torus-Touch. symbiotic_tunnel.vision_horizontal_expand mints SYMBIOTIC_TUNNEL edges from closed-loop tcp/udp mesh using Bayesian-Poisson centroids, inverted-ReLU ADAM, dual-floor mirror, and propeller routing. torus_touch runs continuously (30 s) pushing every Endpoint along the n=7 categorical gap gradient on the toroidal manifold, so tunnel weights follow manifold geometry. 29 unit tests in tests/test_symbiotic_torus.py.",
    "0.17.0": "UEQGM + AI Knowledge Expansion Research Tracks. _EXTENDED_RESEARCH_TOPICS (47 queries, 8 clusters) added to ml_research.py from the active Grok 3 thread: quantum dynamics, biohybrid computing, moiré superlattices, astrophysical timing, AI knowledge graph self-reference, ensemble LLM/RAG, archival AI training, organic data structures. Extended sweep runs before SC loop so foundational physics/AI context precedes supply chain systems engineering acquisition each cycle.",
    "0.17.1": "Grounded Tunneling. grounded_tunneling.py: certainty-anchored expansory pathway collapser. Ground nodes (top-quartile Bayesian certainty) open BFS paths toward uncertain (low-certainty, high-torus-gap) frontiers with RESISTANCE_DURATION weight immunity + torus_amplify torsional boost. Expired paths undergo nodal collapse → new permanent GROUNDED_TUNNEL edge. torus_touch.TouchPressure gains step_multipliers for per-endpoint amplification. _vision_worker Step 5 wires ground_and_expand. 8 new unit tests (TestGroundedTunneling), 38 total, all green. Oracle schema map expanded (Demand Priority Rules, B2B Trading Partners, ECN Tracking, General Ledger Journals, Supply Network maintenance). oracle_schema_mapper.py ADF task panel hardened with computed-style section-header detection and fallback link scraping. Corpus diagnostic (_cohesion_report.py), bilateral Vision<->Touch test harness (_test_bilateral.py), ADAM optimiser unit test (_test_adam.py), Oracle Fusion intersection map (build_intersection_map.py) added. brain_body_signals.py gains 2 quest-comprehension generators (_gen_fallback_parse_warning, _gen_scope_underpowered); knowledge_corpus.py gains SCB Grok conversation ingestor (_ingest_scb_docs) and extended vision scan for SCB docs directory.",
    "0.17.2": "LLaDA2 Sign-Bit Child Acquisition. llada_signbit_children.py maps directionality axes to centered sign bits; sign-bit flips acquire LLaDAChild nodes under high-uncertainty parents, with Model parents seeded from llm_weights and preferred. Child nodes are linked through CHILD_OF, ACQUIRES_CHILD, and SIGNBIT_FLIP edges. _vision_worker Step 6 invokes acquire_llada_signbit_children after grounded tunneling. 11 unit tests cover bit flips, model seeding, child acquisition, idempotency, and generic-parent fallback.",
    "0.17.3": "Bifurcated Tunnel Compute Provisioner (local/virtual, encapsulated). compute_provisioner.py acquires ComputeSlot daemon threads (local compute) + ComputeSlot corpus entities with torus_amplify boosts (virtual compute) from GROUNDED_TUNNEL / LLaDA2 saturation thresholds. Symbiotic closed loop: saturation → slot spawn → torus_amplify written → Touch amplifies slot nodes → more expansory paths → more collapses → more saturation. MAX_SLOTS=8 cap; SLOT_INTERVAL_S=60 (5× faster than vision). CPU overhead model: 748 ops/tick vision + per-slot contribution. _vision_worker Step 7 wired. No external cloud calls — entirely in-process.",    "0.17.4": "Multi-anchor boundary ingestion with polarity alignment. _POLARITY_ALIGN matrix, outward propagation (_propagate_outward), and cross-resource harmonization added to compute_provisioner.py. Coherence selection now picks the highest-polarity-weight anchor across all candidates.",
    "0.17.5": "Harmonious Sign-Bit Flip Boundary Ingestion. Phase 2 ingestion coherence-weighted by SIGNBIT_FLIP convergence: harmonic saturation curve (floor=0.9, ceiling=4.5), HARMONIC_BOND back-edges at proportional weight, ComputeIntent.harmonic_coherence + harmonic_factor fields, heartbeat ingested=/slot_hz=/coherence= fields.",
    "0.17.6": "UEQGM Engine + SiCi Axial Channel. ueqgm_engine.py implements UEQGM v0.9.14 corpus learnings as active Brain computation: sici_axial_decay (\u0394\u03bb_axial = [Si(\u03c6)\u00b7Ci(\u03c6)]\u00b7tan(\u03c6)\u00b7\u0393\u2080), sici_phase_weight (\u00b110% correction via tanh), wavefunction_overlap, floquet_modulation_factor, holographic_entropy, metric_perturbation, phase_evolution_total, entropic_bayesian_step, ueqgm_coherence_score. The SiCi correction is wired into _harmonic_amplify_factor using \u03c6=\u03c0/4+k\u03c0 intersection mapping (tan(\u03c6)=1 always); corpus-backed coherence score scans UEQGM-tagged entities.",}
